
DELETE FROM  PRESENCE CASCADE ;

DELETE FROM  OCCUPANCY CASCADE ;

DELETE FROM  VIRTUAL_SENSOR  CASCADE;

DELETE FROM  VIRTUAL_SENSOR_TYPE CASCADE ;

DELETE FROM  SEMANTIC_OBSERVATION_TYPE  CASCADE;

DELETE FROM  WeMoObservation  CASCADE;

DELETE FROM  WiFiAPObservation  CASCADE;

DELETE FROM  ThermometerObservation  CASCADE;

DELETE FROM  SENSOR  CASCADE;

DELETE FROM  SENSOR_TYPE  CASCADE;

DELETE FROM  COVERAGE_INFRASTRUCTURE  CASCADE;

DELETE FROM  PLATFORM  CASCADE;

DELETE FROM  USER_GROUP_MEMBERSHIP  CASCADE;

DELETE FROM  USER_GROUP  CASCADE;

DELETE FROM  USERS  CASCADE;

DELETE FROM  PLATFORM_TYPE  CASCADE;

DELETE FROM  INFRASTRUCTURE  CASCADE;

DELETE FROM  INFRASTRUCTURE_TYPE  CASCADE;

DELETE FROM  INFRASTRUCTURE_LOCATION CASCADE;

DELETE FROM  LOCATION  CASCADE;