
DELETE FROM  PRESENCE ;

DELETE FROM  OCCUPANCY ;

DELETE FROM  VIRTUAL_SENSOR ;

DELETE FROM  VIRTUAL_SENSOR_TYPE ;

DELETE FROM  SEMANTIC_OBSERVATION_TYPE ;

DELETE FROM  WeMoObservation ;

DELETE FROM  WiFiAPObservation ;

DELETE FROM  ThermometerObservation ;

DELETE FROM  SENSOR ;

DELETE FROM  SENSOR_TYPE ;

DELETE FROM  COVERAGE_INFRASTRUCTURE ;

DELETE FROM  PLATFORM ;

DELETE FROM  USER_GROUP_MEMBERSHIP ;

DELETE FROM  USER_GROUP ;

DELETE FROM  USERS ;

DELETE FROM  PLATFORM_TYPE ;

DELETE FROM  INFRASTRUCTURE ;

DELETE FROM  INFRASTRUCTURE_TYPE ;

DELETE FROM  INFRASTRUCTURE_LOCATION;

DELETE FROM  LOCATION ;